/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductRouteRouteImport } from './routes/product/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as ProductMonthRouteImport } from './routes/product/month'
import { Route as ProductCategoriesRouteImport } from './routes/product/categories'
import { Route as ProductAllRouteImport } from './routes/product/All'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as ProductUpdateProductIdRouteImport } from './routes/product/updateProduct/$id'

const ProductRouteRoute = ProductRouteRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductRouteRoute,
} as any)
const ProductMonthRoute = ProductMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => ProductRouteRoute,
} as any)
const ProductCategoriesRoute = ProductCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ProductRouteRoute,
} as any)
const ProductAllRoute = ProductAllRouteImport.update({
  id: '/All',
  path: '/All',
  getParentRoute: () => ProductRouteRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductRouteRoute,
} as any)
const ProductUpdateProductIdRoute = ProductUpdateProductIdRouteImport.update({
  id: '/updateProduct/$id',
  path: '/updateProduct/$id',
  getParentRoute: () => ProductRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/product': typeof ProductRouteRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/product/All': typeof ProductAllRoute
  '/product/categories': typeof ProductCategoriesRoute
  '/product/month': typeof ProductMonthRoute
  '/product/': typeof ProductIndexRoute
  '/product/updateProduct/$id': typeof ProductUpdateProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/product/$id': typeof ProductIdRoute
  '/product/All': typeof ProductAllRoute
  '/product/categories': typeof ProductCategoriesRoute
  '/product/month': typeof ProductMonthRoute
  '/product': typeof ProductIndexRoute
  '/product/updateProduct/$id': typeof ProductUpdateProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/product': typeof ProductRouteRouteWithChildren
  '/product/$id': typeof ProductIdRoute
  '/product/All': typeof ProductAllRoute
  '/product/categories': typeof ProductCategoriesRoute
  '/product/month': typeof ProductMonthRoute
  '/product/': typeof ProductIndexRoute
  '/product/updateProduct/$id': typeof ProductUpdateProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/product'
    | '/product/$id'
    | '/product/All'
    | '/product/categories'
    | '/product/month'
    | '/product/'
    | '/product/updateProduct/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/product/$id'
    | '/product/All'
    | '/product/categories'
    | '/product/month'
    | '/product'
    | '/product/updateProduct/$id'
  id:
    | '__root__'
    | '/'
    | '/product'
    | '/product/$id'
    | '/product/All'
    | '/product/categories'
    | '/product/month'
    | '/product/'
    | '/product/updateProduct/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductRouteRoute: typeof ProductRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof ProductRouteRoute
    }
    '/product/month': {
      id: '/product/month'
      path: '/month'
      fullPath: '/product/month'
      preLoaderRoute: typeof ProductMonthRouteImport
      parentRoute: typeof ProductRouteRoute
    }
    '/product/categories': {
      id: '/product/categories'
      path: '/categories'
      fullPath: '/product/categories'
      preLoaderRoute: typeof ProductCategoriesRouteImport
      parentRoute: typeof ProductRouteRoute
    }
    '/product/All': {
      id: '/product/All'
      path: '/All'
      fullPath: '/product/All'
      preLoaderRoute: typeof ProductAllRouteImport
      parentRoute: typeof ProductRouteRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof ProductRouteRoute
    }
    '/product/updateProduct/$id': {
      id: '/product/updateProduct/$id'
      path: '/updateProduct/$id'
      fullPath: '/product/updateProduct/$id'
      preLoaderRoute: typeof ProductUpdateProductIdRouteImport
      parentRoute: typeof ProductRouteRoute
    }
  }
}

interface ProductRouteRouteChildren {
  ProductIdRoute: typeof ProductIdRoute
  ProductAllRoute: typeof ProductAllRoute
  ProductCategoriesRoute: typeof ProductCategoriesRoute
  ProductMonthRoute: typeof ProductMonthRoute
  ProductIndexRoute: typeof ProductIndexRoute
  ProductUpdateProductIdRoute: typeof ProductUpdateProductIdRoute
}

const ProductRouteRouteChildren: ProductRouteRouteChildren = {
  ProductIdRoute: ProductIdRoute,
  ProductAllRoute: ProductAllRoute,
  ProductCategoriesRoute: ProductCategoriesRoute,
  ProductMonthRoute: ProductMonthRoute,
  ProductIndexRoute: ProductIndexRoute,
  ProductUpdateProductIdRoute: ProductUpdateProductIdRoute,
}

const ProductRouteRouteWithChildren = ProductRouteRoute._addFileChildren(
  ProductRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductRouteRoute: ProductRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
